routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'User'], function (){
    // Select company
    Route::get('/company/select', 'CompanyController@getSelect');
    Route::post('/company/select', 'CompanyController@postSelect');

    Route::get('/company/register', 'CompanyController@create');
    Route::post('/company/register', 'CompanyController@store');
});

Route::group(['middleware' => ['auth', 'company_selected'], 'namespace' => 'User'], function (){

    Route::get('/home', 'HomeController@index')->name('home');

    // Generalities company
    Route::get('/generalities', 'GeneralityController@show');

    //value chain
    Route::get('/value-chain/data', 'GraphicValueController@index');
    Route::get('/value-chain/graphic', 'GraphicValueController@show');

    //value chain
    Route::get('/supply-chain/data', 'GraphicSupplyController@index');
    Route::get('/supply-chain/graphic', 'GraphicSupplyController@show');

    // Graph events
    Route::get('/supply-chain/graphic/position', 'GraphicSupplyController@updatePosition');
});

Route::group(['middleware' => ['auth','company_selected', 'admin'], 'namespace' => 'Admin'], function (){

    //generalities company edit
    Route::get('/generalities/{id}/edit', 'GeneralityController@edit');
    Route::post('/generalities/{id}/edit', 'GeneralityController@update');

    //value chain
    Route::get('/value-chain', 'ValueController@index');
    Route::post('/activity/create', 'ValueController@store');
    Route::post('/activity/edit', 'ValueController@update');
    Route::get('/activity/{id}/delete', 'ValueController@delete');

    // Supply Chain
    // Provider
    Route::get('/supply-chain/provider', 'SupplyProviderController@index');
    Route::get('/supply-chain/provider/{company_id}/addLevel', 'SupplyProviderController@addLevel');
    Route::get('/supply-chain/provider/{company_id}/removeLevel', 'SupplyProviderController@removeLevel');
    Route::post('/supply-chain/provider/newComponent', 'SupplyProviderController@storeComponent');
    Route::post('/supply-chain/provider/changeComponent', 'SupplyProviderController@updateComponent');
    Route::get('/supply-chain/provider/{component_id}/deleteComponent', 'SupplyProviderController@deleteComponent');
    Route::post('/supply-chain/provider/newRelation', 'SupplyProviderController@storeRelation');
    Route::get('/supply-chain/provider/{relation_id}/deleteRelation', 'SupplyProviderController@deleteRelation');

    // Customer
    Route::get('/supply-chain/customer', 'SupplyCustomerController@index');
    Route::get('/supply-chain/customer/{company_id}/addLevel', 'SupplyCustomerController@addLevel');
    Route::get('/supply-chain/customer/{company_id}/removeLevel', 'SupplyCustomerController@removeLevel');
    Route::post('/supply-chain/customer/newComponent', 'SupplyCustomerController@storeComponent');
    Route::post('/supply-chain/customer/changeComponent', 'SupplyCustomerController@updateComponent');
    Route::get('/supply-chain/customer/{component_id}/deleteComponent', 'SupplyCustomerController@deleteComponent');
    Route::post('/supply-chain/customer/newRelation', 'SupplyCustomerController@storeRelation');
    Route::get('/supply-chain/customer/{relation_id}/deleteRelation', 'SupplyCustomerController@deleteRelation');

    // Users
    Route::get('/users', 'UserController@index');
    Route::get('/users/{id}/activate', 'UserController@activate');
    Route::get('/users/{id}/deactivate', 'UserController@deactivate');
    Route::get('/users/{id}/edit', 'UserController@edit');
    Route::post('/users/{id}/edit', 'UserController@update');
    Route::get('/users/{id}/delete', 'UserController@delete');

    //Companies
    Route::get('/companies', 'CompanyController@index');
    Route::get('/companies/{id}/delete', 'CompanyController@delete');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use softDeletes;


    protected $fillable = [
        'name', 'last_name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getIsAdminAttribute()
    {
        return $this->role == 0;
    }
    public function getIsUserAttribute()
    {
        return $this->role == 1;
    }

    public function getNameLastNameAttribute()
    {
        $name = $this->name;
        $last_name = $this->last_name;
        $first_name = explode(" ",$name);
        $first_last_name = explode(" ",$last_name);

        return $first_name[0]. ' ' .$first_last_name[0];
    }

    public function getRoleNameAttribute() // accessor role_name
    {
        if ($this->role == 0)
            return 'Administrador';
        if ($this->role == 1)
            return 'Usuario estándar';
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('meta_title', 'Inicio | ' . config('app.name'))

@section('section_title', 'Bienvenido')

@section('content')
    <div class="row">
        <div class="col-sm-6">
            <img src="{{ asset('/images/gallery/imagen.jpg') }}" alt="" class="img-thumbnail img-responsive">
        </div>
        <div class="col-sm-5 m-t-40">
            <div class="card-box">
                <div class="text-center">
                    <h4 class="text-uppercase text-success font-600 m-b-0">Bienvenido al sistema de información web</h4>
                </div>
                <div class="panel-body">
                    <p class="font-600 text-justify"></p>
                    <p class="font-600 text-justify">Con el menú vertical de la izquierda podremos manejar
                        diferentes gestiones:</p>
                    <ul class="font-600">
                        <li>Gestión de la cadena de valor.</li>
                        <li>Gestión de la cadena de suministros.</li>
                    </ul>
                    @if(auth()->user()->is_admin)
                    <p class="font-600 text-justify">Y el administrador podrá manejar:</p>
                    <ul class="font-600">
                        <li>Gestión de usuarios.</li>
                        <li>Gestión de empresas.</li>
                    </ul>
                    @endif
                    <p class="font-600 text-justify">Comencemos...</p>
                </div>
            </div>
        </div>
    </div>
@endsection