routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'User'], function (){
    // Select company
    Route::get('/company/select', 'CompanyController@getSelect');
    Route::post('/company/select', 'CompanyController@postSelect');

    Route::get('/company/register', 'CompanyController@create');
    Route::post('/company/register', 'CompanyController@store');
});

Route::group(['middleware' => ['auth', 'company_selected'], 'namespace' => 'User'], function (){

    Route::get('/home', 'HomeController@index')->name('home');

    // Generalities company
    Route::get('/generalities', 'GeneralityController@show');

    //value chain
    Route::get('/value-chain/data', 'GraphicValueController@index');
    Route::get('/value-chain/graphic', 'GraphicValueController@show');

    //value chain
    Route::get('/supply-chain/data', 'GraphicSupplyController@index');
    Route::get('/supply-chain/graphic', 'GraphicSupplyController@show');

    // Graph events
    Route::get('/supply-chain/graphic/position', 'GraphicSupplyController@updatePosition');
});

Route::group(['middleware' => ['auth','company_selected', 'admin'], 'namespace' => 'Admin'], function (){

    //generalities company edit
    Route::get('/generalities/{id}/edit', 'GeneralityController@edit');
    Route::post('/generalities/{id}/edit', 'GeneralityController@update');

    //value chain
    Route::get('/value-chain', 'ValueController@index');
    Route::post('/activity/create', 'ValueController@store');
    Route::post('/activity/edit', 'ValueController@update');
    Route::get('/activity/{id}/delete', 'ValueController@delete');

    // Supply Chain
    // Provider
    Route::get('/supply-chain/provider', 'SupplyProviderController@index');
    Route::get('/supply-chain/provider/{company_id}/addLevel', 'SupplyProviderController@addLevel');
    Route::get('/supply-chain/provider/{company_id}/removeLevel', 'SupplyProviderController@removeLevel');
    Route::post('/supply-chain/provider/newComponent', 'SupplyProviderController@storeComponent');
    Route::post('/supply-chain/provider/changeComponent', 'SupplyProviderController@updateComponent');
    Route::get('/supply-chain/provider/{component_id}/deleteComponent', 'SupplyProviderController@deleteComponent');
    Route::post('/supply-chain/provider/newRelation', 'SupplyProviderController@storeRelation');
    Route::get('/supply-chain/provider/{relation_id}/deleteRelation', 'SupplyProviderController@deleteRelation');

    // Customer
    Route::get('/supply-chain/customer', 'SupplyCustomerController@index');
    Route::get('/supply-chain/customer/{company_id}/addLevel', 'SupplyCustomerController@addLevel');
    Route::get('/supply-chain/customer/{company_id}/removeLevel', 'SupplyCustomerController@removeLevel');
    Route::post('/supply-chain/customer/newComponent', 'SupplyCustomerController@storeComponent');
    Route::post('/supply-chain/customer/changeComponent', 'SupplyCustomerController@updateComponent');
    Route::get('/supply-chain/customer/{component_id}/deleteComponent', 'SupplyCustomerController@deleteComponent');
    Route::post('/supply-chain/customer/newRelation', 'SupplyCustomerController@storeRelation');
    Route::get('/supply-chain/customer/{relation_id}/deleteRelation', 'SupplyCustomerController@deleteRelation');

    // Users
    Route::get('/users', 'UserController@index');
    Route::get('/users/{id}/activate', 'UserController@activate');
    Route::get('/users/{id}/deactivate', 'UserController@deactivate');
    Route::get('/users/{id}/edit', 'UserController@edit');
    Route::post('/users/{id}/edit', 'UserController@update');
    Route::get('/users/{id}/delete', 'UserController@delete');

    //Companies
    Route::get('/companies', 'CompanyController@index');
    Route::get('/companies/{id}/delete', 'CompanyController@delete');
});

app/SupplyChainCustomerRelation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SupplyChainCustomerRelation extends Model
{
    public function origin()
    {
        return $this->belongsTo(SupplyChainCustomer::class, 'origin_customer_id');
    }

    public function destiny()
    {
        return $this->belongsTo(SupplyChainCustomer::class, 'destiny_customer_id');
    }

    public function getNameRelationAttribute()
    {
        return $this->origin->name.' ('.$this->origin->level.')'.' - '.$this->destiny->name.' ('.$this->destiny->level.')';
    }

}

app/Http/Controllers/Admin/SupplyCustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Company;
use App\SupplyChainCustomer;
use App\SupplyChainCustomerRelation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SupplyCustomerController extends Controller
{
    public function byOrigin($id)
    {

        $customer = SupplyChainCustomer::find($id);
        $company_id = $customer->company_id;
        $level = $customer->level +1;
        return SupplyChainCustomer::where('level', $level)->where('company_id', $company_id)->get();
    }

    public function index()
    {
        $company_id = session('company_id');
        $company = Company::find($company_id);
        $components = SupplyChainCustomer::where('company_id', $company->id)->get();
        foreach ($components as $component){
            $component_id = $component->id;
            $component->editable = SupplyChainCustomerRelation::where('origin_customer_id', $component_id)->orWhere('destiny_customer_id', $component_id)->exists();
        }
        $relations = SupplyChainCustomerRelation::where('company_id', $company_id)->get();
        return view('admin.supply-customer.index')->with(compact('company', 'components', 'relations'));
    }

    public function addLevel($id)
    {
        $addLevel = Company::find($id);
        $addLevel->customer_levels_count+=1;
        $addLevel->save();

        $notification = 'Se agregó un nuevo nivel';
        return back()->with(compact('notification'));
    }

    public function removeLevel($id)
    {
        $removeLevel = Company::find($id);
        $levelExists = SupplyChainCustomer::where('level', $removeLevel->customer_levels_count)->where('company_id', $id)->exists();

        if (! $levelExists){
            $removeLevel->customer_levels_count-=1;
            $removeLevel->save();

            return back()->with('notification', 'Se eliminó correctamente el nivel');
        }else{
            return back()->with('error', 'No se puede eliminar el nivel '.$removeLevel->customer_levels_count.' porque existe componentes de este nivel');
        }
    }

    public function storeComponent(Request $request)
    {
        $component = new SupplyChainCustomer();
        $component->name = $request->input('name');
        $component->level = $request->input('level');
        $component->company_id = session('company_id');
        $component->user_id = auth()->id();
        $component->save();

        $notification = 'Se registró correctamente el nuevo componente';
        return back()->with(compact('notification'));
    }

    public function updateComponent(Request $request)
    {
        $id = $request->input('component_id');

        $component = SupplyChainCustomer::find($id);
        $component->name = $request->input('name');
        $level = $request->input('level');
        if($level)
            $component->level = $level;
        $component->save();

        return back()->with('notification', 'El componente fue modificado correctamente');
    }

    public function deleteComponent($id)
    {
        $componentExists = SupplyChainCustomerRelation::where('origin_customer_id', $id)->orWhere('destiny_customer_id', $id)->exists();
        $component = SupplyChainCustomer::find($id);
        if (! $componentExists){

            $component->delete();

            return back()->with('notification', 'Se eliminó correctamente el componente');
        }else{
            return back()->with('error', 'No se puede eliminar el componente '.$component->name.' porque existe en las relaciones');
        }

    }

    public function storeRelation(Request $request)
    {
        $origin_id = $request->input('origin_id');
        $destiny_id = $request->input('destiny_id');
        $componentExists = SupplyChainCustomerRelation::where('origin_customer_id', $origin_id)
                                                    ->where('destiny_customer_id', $destiny_id)->exists();

        if (!$componentExists) {

            $component = new SupplyChainCustomerRelation();
            $component->origin_customer_id = $origin_id;
            $component->destiny_customer_id = $destiny_id;
            $component->company_id = session('company_id');
            $component->user_id = auth()->id();
            $component->save();

            return back()->with('notification', 'Se registró exitosamente la relación');
        }else{
            return back()->with('error', 'La relación ya está registrada');
    }
    }

    public function deleteRelation($relation_id)
    {
        $relation = SupplyChainCustomerRelation::find($relation_id);
        $relation->delete();
        return back()->with('notification', 'Se eliminó exitosamente la relación');
    }
}

resources/views/admin/supply-customer/index.blade.php
@extends('layouts.app')

@section('meta_title', 'Datos de la cadena de suministro: Cliente | '.$company->name.' | '  . config('app.name'))

@section('section_title', 'Datos de la cadena de suministro: Cliente')

@section('styles')
    <!-- Custom box css -->
    <link href="{{ asset('/plugins/custombox/dist/custombox.min.css') }}" rel="stylesheet">

    <link href="{{ asset('/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css') }}" rel="stylesheet" />
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-5">
            <div class="card-box">
                <div class="pull-right hidden-print">
                    <a href="{{ url('/supply-chain/customer/'.$company->id.'/addLevel') }}" class="btn btn-sm btn-primary waves-effect waves-light">
                        Agregar nivel
                    </a>
                </div>
                <h4 class="header-title m-t-0 m-b-30">Niveles de la cadena de suministro</h4>
                <table class="table table-bordered table-hover m-0">
                    <thead>
                    <tr class="active">
                        <th>Niveles del cliente</th>
                        <th class="hidden-print text-center col-sm-3">Opción</th>
                    </tr>
                    </thead>
                    <tbody>
                    @for ($i=1; $i<= $company->customer_levels_count; ++$i)
                    <tr>
                        <td>Nivel {{ $i }}</td>
                        @if($i == $company->customer_levels_count)
                            <td class="hidden-print text-center">
                                <a href="{{ url('/supply-chain/customer/'.$company->id.'/removeLevel') }}" class="btn btn-sm btn-danger" title="Eliminar" onclick="return confirm('¿Estas seguro que quieres eliminar?')">
                                    <i class="fa fa-trash o"></i>
                                </a>
                            </td>
                        @else
                            <td class="hidden-print text-center">
                                <button class="btn btn-sm btn-danger" title="No se puede eliminar sin eliminar el nivel más alto" disabled>
                                    <i class="fa fa-trash o"></i>
                                </button>
                            </td>
                        @endif
                    </tr>
                    @endfor
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-7">
            <div class="card-box">
                <div class="pull-right hidden-print">
                    <button class="btn btn-sm btn-primary waves-effect waves-light" data-toggle="modal" data-target="#new-component">
                        Nuevo
                    </button>
                </div>
                <h4 class="header-title m-t-0 m-b-30">Componentes de la cadena de suministro</h4>
                <table class="table table-bordered table-hover m-0">
                    <thead>
                    <tr class="active">
                        <th>Nombre</th>
                        <th class="text-center">Nivel</th>
                        <th class="hidden-print text-center col-sm-3">Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($components as $component)
                        <tr>
                            <td>{{ $component->name }}</td>
                            <td class="text-center">{{ $component->level }}</td>
                            <td class="hidden-print text-center">
                                <button type="button" class="btn btn-sm btn-success" title="Editar"
                                        data-component="{{ $component->id }}" @if($component->editable) data-editable="1" @else data-editable="0" @endif>
                                    <i class="fa fa-edit"></i>
                                </button>
                                <a href="{{ url('/supply-chain/customer/'.$component->id.'/deleteComponent') }}" class="btn btn-sm btn-danger" title="Eliminar" onclick="return confirm('¿Estas seguro que quieres eliminar?')">
                                    <i class="fa fa-trash o"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <div class="card-box">
                <div class="pull-right hidden-print">
                    <button class="btn btn-sm btn-primary waves-effect waves-light" data-toggle="modal" data-target="#new-relation">
                        Nuevo
                    </button>
                </div>
                <h4 class="header-title m-t-0 m-b-30">Relaciones "Cliente de Cliente"</h4>
                <table class="table table-bordered table-hover m-0">
                    <thead>
                    <tr class="active">
                        <th>Relación Origen - Destino</th>
                        <th class="text-center">Origen</th>
                        <th class="text-center">Destino</th>
                        <th class="hidden-print text-center col-sm-2">Opción</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($relations as $relation)
                        <tr>
                            <td>{{ $relation->name_relation }}</td>
                            <td class="text-center">{{ $relation->origin->name }}</td>
                            <td class="text-center">{{ $relation->destiny->name }}</td>
                            <td class="hidden-print text-center">
                                <a href="{{ url('/supply-chain/customer/'.$relation->id.'/deleteRelation') }}" class="btn btn-sm btn-danger" title="Eliminar" onclick="return confirm('¿Estas seguro que quieres eliminar?')">
                                    <i class="fa fa-trash o"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="hidden-print">
        <div class="pull-right">
            <a href="javascript:window.print()" class="btn btn-purple btn-rounded btn-bordred waves-effect waves-light"><i class="fa fa-print m-r-5"></i>Imprimir</a>
        </div>
    </div>

    <div id="new-component" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Registrar nuevo componente</h4>
                </div>
                <form class="form-group" role="form" action="{{ url('/supply-chain/customer/newComponent') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <label for="name" class="control-label">Nombre de la actividad</label>
                                    <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}" required>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <label for="level">Seleccione nivel</label>
                                <select id="level" name="level" class="form-control" required>
                                    @for ($i=1; $i<= $company->customer_levels_count; ++$i)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{--modal new relation--}}
    <div id="new-relation" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Registrar nueva relación</h4>
                </div>
                <form class="form-group" role="form" action="{{ url('/supply-chain/customer/newRelation') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <select name="origin_id" class="form-control"  id="select-origin">
                                    <option value="">Seleccione origen</option>
                                    @foreach ($components as $component)
                                        <option value="{{ $component->id }}">{{ $component->name }} ({{ $component->level }})</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-sm-6">
                                <select name="destiny_id" class="form-control"  id="select-destiny">
                                    <option value="">Seleccione destino</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary waves-effect waves-light">Registrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{--modal edit component--}}
    <div class="modal fade" tabindex="-1" role="dialog" id="modalComponent">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Editar componente</h4>
                </div>
                <form action="{{ url('/supply-chain/customer/changeComponent') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <input type="hidden" name="component_id" id="component_id" value="">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <label for="component_name" class="control-label">Nombre de la actividad</label>
                                    <input type="text" class="form-control" name="name" id="component_name" value="{{ old('name') }}" required>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <label for="component_level">Seleccione nivel</label>
                                <select id="component_level" name="level" class="form-control" disabled>
                                    @for ($i=1; $i<= $company->customer_levels_count; ++$i)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <!-- Modal-Effect -->
    <script src="{{ asset('/plugins/custombox/dist/custombox.min.js') }}"></script>
    <script src="{{ asset('/plugins/custombox/dist/legacy.min.js"><') }}"></script>

    <script src="{{ asset('/js/admin/supply/edit.js') }}"></script>

    <script src="{{ asset('/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js') }}" type="text/javascript"></script>
    <script>
        $("input[name='demo3']").TouchSpin({
            buttondown_class: "btn btn-primary",
            buttonup_class: "btn btn-primary"
        });
    </script>
@endsection